### ISSUE TITLE
Make the plugin to look for the entire folder rather than the individual file 

### ISSUE THREAD

**Issue by sendilkumarn** [catsigma/parcel-plugin-wasm.rs#1]
@catsigma Let us make the plugin to look for the entire folder `crate/pkg` (created by wasm-pack) rather than looking at the specific rust file.

Just like https://github.com/wasm-tool/wasm-pack-plugin 

WDYT?

cc: @fitzgen

**Comment by catsigma** [comment]
Don’t know if I can bind the pkg folder in Parcel. Currently, I hook the rs file to the plugin.

I’ll have an experiment on this.

Thanks.



Thursday, September 27, 2018, 15:48 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by sendilkumarn** [comment]
Perfect. @catsigma let me know if there is anything that I can help with. ( but I am a complete newbie in parcel)

**Comment by fitzgen** [comment]
If it has to require a specific file, I suggest using the `Cargo.toml`. `src/lib.rs` is the convention, but the entry point to a library can be arbitrary and configured in `Cargo.toml`.

The `Cargo.toml` -- on the other hand -- is representative of the whole crate that is being compiled to wasm.

**Comment by catsigma** [comment]
I've figured out a solution.

Let the plugin generates an empty `.rustwasm` file automaticlly aside the `node_modules` folder.

In JS file
```
import { foo } from 'path/to/.rustwasm'
```

**Comment by catsigma** [comment]
Sorry, I've found a way to fallback to origin TOML file assets. Now we can just import from `Cargo.toml`.

@sendilkumarn @fitzgen

**Comment by catsigma** [comment]
fixed  @ version "1.2.0"

**Comment by sendilkumarn** [comment]
Thanks @catsigma
