### ISSUE TITLE
Plugin emits Cargo.toml or *.rs in build

### ISSUE THREAD

**Issue by mysterycommand** [catsigma/parcel-plugin-wasm.rs#16]
Hi there, it looks to me like this plugin is extraneously emitting the `Cargo.toml` or `*.rs` file that's imported into a parcel entry, along with the built `*_bg.wasm` and the `*.js` bundle. For example:
```sh
$ tree src/
src/
├── entry.ts # imports lib.rs and style.css
├── index.html # a script tag loads entry.ts
├── lib.rs
└── style.css
```

Building this with `parcel build src/index.html` generates this dist:
```sh
$ tree dist/
dist/
├── entry.4f7fdf66.css # minified, processed, etc. style.css
├── entry.553003c9.js # minified, processed, etc. entry.ts + deps (wasm loader, etc)
├── ferric_bg.c03385a6.wasm # the wasm binary
├── index.html # minified, processed, etc. index.html
└── lib.f76eae7b.rs # unminified, unprocessed, just straightup copied … by accident? I don't think it's necessary
```

The same thing happens if I try to `import { whatever } from '../Cargo.toml'` in `src/entry.ts` … that is, a hashed, but otherwise unminified and unprocessed copy of `Cargo.toml` winds up in the build. It's not a huge deal, it's not being loaded/required by anything, it's just extra and I'd prefer my dist to have only the absolutely necessary assets.

If this is something you'd be interested in fixing I might be able to put a PR together, but I've never built a Parcel plugin before so any pointers as to where in the `Asset` class the list of files to process/emit is created would be super helpful.

**Comment by catsigma** [comment]
Thanks for the issue. Actually this may cause by the dependencies Parcel collected in the process. I don't know how to avoid the copy yet. 

I suggest that you can create an shell script to removed the *.rs files after the build to solve this issue without modifying the plugin.

**Comment by mysterycommand** [comment]
Hmm, thanks for the feedback. I think there _must_ be a way to do this in the plugin though since (for example) `import`ing `style.scss` in my `entry.ts` emits an `entry.<hash>.css` and `entry.<hash>.css.map`, but no `style.<hash>.scss`.

Anyway, if you're open to reviewing a PR I'll do a little more poking around and see if I can come up with a solution.

**Comment by catsigma** [comment]
No problem, I’ll merge it if you post the fix.




Thursday, April 4, 2019, 04:12 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by mysterycommand** [comment]
Hi @catsigma … I am fully prepared to accept that I may have gone completely off the deep end on this trying to not emit a completely harmless file, but I wound up learning a lot about Parcel and wasm-pack and came up with an alternative plugin that has some interesting characteristics. You can check it out (if you feel so inclined) here:

https://github.com/mysterycommand/parcel-plugin-wasm-pack

While I think I've kept to the spirit of your plugin, I made a couple of changes:

1. I tried to reuse as much of Parcel's `RustAsset` and `TOMLAsset` as possible by [pulling in their classes](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L8-L9) and [calling](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L53) [in](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L58) [to](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L66) [their](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L119) [prototypes](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L124) where possible
2. I also tried to reuse as much of `wasm-pack`'s output as possible … this involved digging into `wasm-pack`'s [`--target no-modules`](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html#without-a-bundler) … which it turns out is almost identical to the loader that your plugin builds (albeit inside an IIFE, and with only the web target's `init` function provided)
3. I added [`const { TextEncoder, TextDecoder } = require('util');`](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L309) to the loader in the "non-browser" case (since Node and Electron both have a node env I think this should be fine, but I haven't tested it in Electron) … without this running Parcel with the `node` target (I think a pretty small edge case tbh) will fail
4. I used [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to log `wasm-pack`'s [progress](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.js#L24) (also [here](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.js#L35)) to Parcel's console
    - I also added a bunch of `verbose` logs during this whole process and left the useful ones in there, they'll only show up if `--log-level` is 5 … I think … I actually think maybe [Parcel's docs](https://parceljs.org/cli.html#change-log-level) are maybe a bit out of date on this
5. I only implemented support for running this through `wasm-pack` … no direct `wasm-bindgen` fallback, but it does still check if `wasm-bindgen` is installed and will run `-m no-install` if possible
6. I am honestly not sure how, but this plugin is not emitting the extra file in the build … honestly, I have no real idea what you're doing (or not) that I'm not (or am) … :meme_smile:

All that said I'm not at all trying to step on your toes, and def. could not have done this without your excellent reference implementation. I'd be happy to submit PRs bringing any of these changes that you like into this repo. I just didn't want to submit some big crazy PR with maybe questionable importing of "private" classes and probably brittle rewriting of `wasm-pack`'s possibly deprecated `no-modules` output.

Anyway, if you have some time I'd love to hear what you think of my plugin, and just let me know if you want me to try and bring any of this stuff to yours. I guess, feel free to close this issue? I hope you're having a great weekend!

**Comment by catsigma** [comment]
Thanks for the reply.

This Parcel plugin was initially created several months ago and recently I'm not working with rust-lang, so it could be a little outdated to both Parcel and wasm-pack. 

Currently I don't have too much time to tidy and check the codes, so RP with many changes may not be suitable for me, sry.

But your plugin is great to try to reuse the most of them, and I hope I can do that with some refactor works in the feature.
