### ISSUE TITLE
Cannot resolve dependency with stdweb

### ISSUE THREAD

**Issue by AThilenius** [catsigma/parcel-plugin-wasm.rs#20]
Firstly, thank you for your work on this plugin!

If you add `stdweb` to the Cargo.toml and use it, a `Cannot resolve dependency` error will be thrown despite the file existing. I created a minimal repro (with a README) here: https://github.com/AThilenius/parcel-wasm-bindgen-stdweb

I've been trying to get `parcel` + `wasm-bindgen` + `stdweb` working all day and have tried a lot of different options, including a lot of attempts not using this plugin (trying to load the `wasm-pack` pkg directly). Parcel's built-in WASM support seems to clash pretty hard with the `wasm-pack` output, especially when it's generating code `stdweb` macros.

**Comment by catsigma** [comment]
Issue solved in version 1.2.11
