### ISSUE TITLE
Feature request: build --debug as default.

### ISSUE THREAD

**Issue by extraymond** [catsigma/parcel-plugin-wasm.rs#23]
Hi! Thx for creating this awesome tool. Just discovered something accidentally.

Since user might use parcel to build not only rust but also html/css/js, it might makes more sense to trigger ```wasm-pack build --debug``` instead of [release as default](https://github.com/rustwasm/wasm-pack/issues/437). So parcel users will have expected behavior between start(dev) and build(release).

This change might help users speedup compile time during dev therefore having better dev experience when programming in rust.

**Comment by catsigma** [comment]
A new version 1.2.13 has been released to solve this issue.

Now you can use `WASM_PACK_PROFILE=dev parcel src/index.html` to enable the dev profile for wasm-pack.

**Comment by extraymond** [comment]
Thx!!!
