### ISSUE TITLE
No access to _bg.wasm itself?

### ISSUE THREAD

**Issue by rbtcollins** [catsigma/parcel-plugin-wasm.rs#25]
Perhaps I'm missing something - but how does one access the underlying wasm object, for instance as the bindgen game of life tutorial does for exporting the memory arena? With the webpack example the way is clear; its not so clear with this parcel plugin.

**Comment by catsigma** [comment]
Thanks for this issue.

Now you can access `memory` in the version: 1.2.15

```
import lib from 'path/to/Cargo.toml'
console.log(lib.wasm)    // all the origin wasm import data here
console.log(lib.wasm.memory)
```

**Comment by rbtcollins** [comment]
Thank you! <3
