### ISSUE TITLE
Broken with latest version of wasm-bindgen

### ISSUE THREAD

**Issue by Pauan** [catsigma/parcel-plugin-wasm.rs#30]
This was first reported here: https://github.com/rustwasm/wasm-bindgen/issues/2120

The problem is that wasm-bindgen changed its code generation, and since this plugin does [custom parsing of the JS code](https://github.com/catsigma/parcel-plugin-wasm.rs/blob/c3f73fe4f8aac4adda75cd9de4fcbe68c9172350/WASMbindgenAsset.js#L149), that is now broken.

In addition, wasm-bindgen now generates a `foo_bg.js` file (rather than `foo.js`), so the [file path needs to be updated as well](https://github.com/catsigma/parcel-plugin-wasm.rs/blob/c3f73fe4f8aac4adda75cd9de4fcbe68c9172350/WASMbindgenAsset.js#L143).

However, most of this complexity can be avoided by using `--target web`. Then it wouldn't need to do custom parsing, and it wouldn't need a [custom init section](https://github.com/catsigma/parcel-plugin-wasm.rs/blob/c3f73fe4f8aac4adda75cd9de4fcbe68c9172350/WASMbindgenAsset.js#L187-L224) either.

**Comment by kaoet** [comment]
Temporary workaround: in your `Cargo.toml`:
```
[dependencies]
wasm-bindgen = "0.2, <0.2.61"
```

That keeps you away from the broken `0.2.61+` version.
